runtime: python37
entrypoint: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker
automatic_scaling:
  max_instances: 4

handlers:
- url: /
  static_files: frontend/Startseite.html
  upload: frontend/Startseite.html
  secure: always

- url: /images
  static_dir: frontend/images
- url: /(.*\.(css|html|js|txt))$
  static_files: frontend/\1
  upload: frontend/.*\.(css|html|js|txt)$

